/**
 * Commerce response schemas. The definitions live in `@prabhix/oneops-api` (generated from
 * oneOps/backend/apidocs.json plus shared Zod at the response boundary). This file re-exports
 * so existing `@/lib/schemas/commerce` imports keep working.
 */
export {
  billingIntervalSchema,
  cartViewSchema,
  categoryListSchema,
  categoryViewSchema,
  cursorPageSchema,
  customerDetailSchema,
  customerListPageSchema,
  customerSummarySchema,
  dashboardViewSchema,
  discountListSchema,
  discountTypeSchema,
  discountViewSchema,
  downloadLinkResponseSchema,
  downloadListSchema,
  downloadViewSchema,
  orderDetailSchema,
  orderItemSchema,
  orderListPageSchema,
  orderSummarySchema,
  productDetailSchema,
  productListPageSchema,
  productStatusSchema,
  productSummarySchema,
  productTypeSchema,
  refundViewSchema,
  settingsViewSchema,
  variantViewSchema,
  type BillingInterval,
  type CartView,
  type CategoryView,
  type CommerceSettings,
  type DiscountView,
  type OrderDetail,
  type OrderSummary,
  type ProductDetail,
  type ProductStatus,
  type ProductSummary,
  type ProductType,
  type VariantView,
} from "@prabhix/oneops-api";
